/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalisesRouteImport } from './routes/catalises'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as NarrativasRouteImport } from './routes/narrativas'
import { Route as XrayRouteImport } from './routes/xray'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalisesRoute = CatalisesRouteImport.update({
  id: '/catalises',
  path: '/catalises',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrativasRoute = NarrativasRouteImport.update({
  id: '/narrativas',
  path: '/narrativas',
  getParentRoute: () => rootRouteImport,
} as any)
const XrayRoute = XrayRouteImport.update({
  id: '/xray',
  path: '/xray',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalises': typeof CatalisesRoute
  '/diario': typeof DiarioRoute
  '/narrativas': typeof NarrativasRoute
  '/xray': typeof XrayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalises': typeof CatalisesRoute
  '/diario': typeof DiarioRoute
  '/narrativas': typeof NarrativasRoute
  '/xray': typeof XrayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalises': typeof CatalisesRoute
  '/diario': typeof DiarioRoute
  '/narrativas': typeof NarrativasRoute
  '/xray': typeof XrayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalises' | '/diario' | '/narrativas' | '/xray'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalises' | '/diario' | '/narrativas' | '/xray'
  id: '__root__' | '/' | '/catalises' | '/diario' | '/narrativas' | '/xray'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalisesRoute: typeof CatalisesRoute
  DiarioRoute: typeof DiarioRoute
  NarrativasRoute: typeof NarrativasRoute
  XrayRoute: typeof XrayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalises': {
      id: '/catalises'
      path: '/catalises'
      fullPath: '/catalises'
      preLoaderRoute: typeof CatalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narrativas': {
      id: '/narrativas'
      path: '/narrativas'
      fullPath: '/narrativas'
      preLoaderRoute: typeof NarrativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xray': {
      id: '/xray'
      path: '/xray'
      fullPath: '/xray'
      preLoaderRoute: typeof XrayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalisesRoute: CatalisesRoute,
  DiarioRoute: DiarioRoute,
  NarrativasRoute: NarrativasRoute,
  XrayRoute: XrayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
